language: python
python:
  - "2.7"
git:
  depth: 1
env:
  global:
    - secure: "hXNhTinvLDlfiIWxNgnxDFtL1zOnPd1TMyUkLLjqTRBbcuVinlMLISRgYV9g\nIIvLPG5S424ybNtU1X7X9MlypDmvis3/+G8gBo2q+7IRTAKw1C2J9/6RhIaG\nnD4aV9YZKmyz8pH1DZj6AMFIqY+2+W4Wte3oyL8IqbFRMfhdmzE="
# command to install dependencies
install: "pip install -q -r requirements.txt --use-mirrors"
# This is needed, otherwise, nosetests can't find the installed pymatgen C
# extensions.
before_script:
  - python setup.py --quiet install
  - mv pymatgen pmg
# command to run tests, e.g. python setup.py test
script: nosetests pmg/matproj/tests
branches:
  only:
    - master
    - stable
notifications:
  email:
    recipients:
      - shyuep@gmail.com
    on_success: change
    on_failure: always
